export const MEMORY_LIST_REQUEST = 'MEMORY_LIST_REQUEST';
export const MEMORY_LIST_SUCCESS = 'MEMORY_LIST_SUCCESS';
export const MEMORY_LIST_FAIL = 'MEMORY_LIST_FAIL';

export const MEMORY_CREATE_REQUEST = 'MEMORY_CREATE_REQUEST';
export const MEMORY_CREATE_SUCCESS = 'MEMORY_CREATE_SUCCESS';
export const MEMORY_CREATE_FAIL = 'MEMORY_CREATE_FAIL';

export const MEMORY_LIKE_REQUEST = 'MEMORY_LIKE_REQUEST';
export const MEMORY_LIKE_SUCCESS = 'MEMORY_LIKE_SUCCESS';
export const MEMORY_LIKE_FAIL = 'MEMORY_LIKE_FAIL';

export const MEMORY_FETCH_REQUEST = 'MEMORY_FETCH_REQUEST';
export const MEMORY_FETCH_SUCCESS = 'MEMORY_FETCH_SUCCESS';
export const MEMORY_FETCH_FAIL = 'MEMORY_FETCH_FAIL';
export const MEMORY_FETCH_RESET = 'MEMORY_FETCH_RESET';

export const MEMORY_UPDATE_REQUEST = 'MEMORY_UPDATE_REQUEST';
export const MEMORY_UPDATE_SUCCESS = 'MEMORY_UPDATE_SUCCESS';
export const MEMORY_UPDATE_FAIL = 'MEMORY_UPDATE_FAIL';

export const MEMORY_DELETE_REQUEST = 'MEMORY_DELETE_REQUEST';
export const MEMORY_DELETE_SUCCESS = 'MEMORY_DELETE_SUCCESS';
export const MEMORY_DELETE_FAIL = 'MEMORY_DELETE_FAIL';