export const MEMORY_LIST_REQUEST = 'MEMORY_LIST_REQUEST';
export const MEMORY_LIST_SUCCESS = 'MEMORY_LIST_SUCCESS';
export const MEMORY_LIST_FAIL = 'MEMORY_LIST_FAIL';

export const MEMORY_CREATE_REQUEST = 'MEMORY_CREATE_REQUEST';
export const MEMORY_CREATE_SUCCESS = 'MEMORY_CREATE_SUCCESS';
export const MEMORY_CREATE_FAIL = 'MEMORY_CREATE_FAIL';

export const MEMORY_UPDATE_REQUEST = 'MEMORY_UPDATE_REQUEST';
export const MEMORY_UPDATE_SUCCESS = 'MEMORY_UPDATE_SUCCESS';
export const MEMORY_UPDATE_FAIL = 'MEMORY_UPDATE_FAIL';

export const MEMORY_DELETE_REQUEST = 'MEMORY_DELETE_REQUEST';
export const MEMORY_DELETE_SUCCESS = 'MEMORY_DELETE_SUCCESS';
export const MEMORY_DELETE_FAIL = 'MEMORY_DELETE_FAIL';